name: Docker Build and Push Development

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  IMAGE_NAME: artist3/gamic-landing-dev:latest
  NEXT_REDIRECT_URL: https://web.gamic.pro/

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        build-args: |
          NEXT_TELEMETRY_DISABLED=1
          NEXT_LINT_DURING_BUILD=false
          NEXT_REDIRECT_URL: https://web.gamic.pro/
        tags: |
          artist3/gamic-landing-dev:latest
          artist3/gamic-landing-dev:${{ github.sha }}